truncate table state;

insert into state (id, uf, name) values (1, 'SP', 'São Paulo');
insert into state (id, uf, name) values (2, 'MG', 'Minas Gerais');
insert into state (id, uf, name) values (3, 'RJ', 'Rio de Janeiro');
insert into state (id, uf, name) values (4, 'BA', 'Bahia');
insert into state (id, uf, name) values (5, 'RS', 'Rio Grande do Sul');
insert into state (id, uf, name) values (6, 'PR', 'Paraná');
insert into state (id, uf, name) values (7, 'PE', 'Pernambuco');
insert into state (id, uf, name) values (8, 'CE', 'Ceará');
insert into state (id, uf, name) values (9, 'PA', 'Pará');
insert into state (id, uf, name) values (10, 'MA', 'Maranhão');
insert into state (id, uf, name) values (11, 'SC', 'Santa Catarina');
insert into state (id, uf, name) values (12, 'GO', 'Goiás');
insert into state (id, uf, name) values (13, 'PB', 'Paraíba');
insert into state (id, uf, name) values (14, 'AM', 'Amazonas');
insert into state (id, uf, name) values (15, 'ES', 'Espírito Santo');
insert into state (id, uf, name) values (16, 'RN', 'Rio Grande do Norte');
insert into state (id, uf, name) values (17, 'AL', 'Alagoas');
insert into state (id, uf, name) values (18, 'MT', 'Mato Grosso');
insert into state (id, uf, name) values (19, 'PI', 'Piauí');
insert into state (id, uf, name) values (20, 'DF', 'Distrito Federal');
insert into state (id, uf, name) values (21, 'MS', 'Mato Grosso do Sul');
insert into state (id, uf, name) values (22, 'SE', 'Sergipe');
insert into state (id, uf, name) values (23, 'RO', 'Rondônia');
insert into state (id, uf, name) values (24, 'TO', 'Tocantins');
insert into state (id, uf, name) values (25, 'AC', 'Acre');
insert into state (id, uf, name) values (26, 'AP', 'Amapá');
insert into state (id, uf, name) values (27, 'RR', 'Roraima');
